# Generated by Django 3.1.2 on 2020-10-18 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(max_length=1)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.date')),
                ('postcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postcode')),
            ],
        ),
        migrations.CreateModel(
            name='Chart2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.CharField(max_length=200)),
                ('values', models.CharField(max_length=200)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.date')),
                ('postcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postcode')),
            ],
        ),
        migrations.CreateModel(
            name='Chart1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detached_avg', models.IntegerField()),
                ('semidetached_avg', models.IntegerField()),
                ('terraced_avg', models.IntegerField()),
                ('flats_avg', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.date')),
                ('postcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postcode')),
            ],
        ),
    ]
